//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int idBooking { get; set; }
        public int idHotel { get; set; }
        public int id { get; set; }
        public System.DateTime dateBoking { get; set; }
        public int numNights { get; set; }
        public int numPerson { get; set; }
        public int finalPrice { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
