//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int idComment { get; set; }
        public int id { get; set; }
        public int idHotel { get; set; }
        public string text { get; set; }
    }
}
